/**
 * Skill library — 50+ skills across the four spec categories.
 *
 * Aliases implement the normalization requirement ("MS Excel" -> "Excel").
 * Slugs are the stable identifiers used by career mappings.
 */

export interface SkillSeed {
  name: string;
  slug: string;
  category: 'Technical' | 'Analytical' | 'Tools' | 'Soft skills';
  description: string;
  aliases: string[];
}

export const SKILLS: SkillSeed[] = [
  // ─── Technical ──────────────────────────────────────────────────────────
  {
    name: 'Python',
    slug: 'python',
    category: 'Technical',
    description: 'General-purpose programming used across data and backend work.',
    aliases: ['python3', 'py'],
  },
  {
    name: 'SQL',
    slug: 'sql',
    category: 'Technical',
    description: 'Querying relational databases and writing correct joins.',
    aliases: ['structured query language', 't-sql'],
  },
  {
    name: 'JavaScript',
    slug: 'javascript',
    category: 'Technical',
    description: 'Language of the browser and the Node.js runtime.',
    aliases: ['js', 'ecmascript'],
  },
  {
    name: 'TypeScript',
    slug: 'typescript',
    category: 'Technical',
    description: 'Typed JavaScript for larger applications.',
    aliases: ['ts'],
  },
  {
    name: 'React',
    slug: 'react',
    category: 'Technical',
    description: 'Component-based UI library for web applications.',
    aliases: ['react.js', 'reactjs'],
  },
  {
    name: 'Node.js',
    slug: 'nodejs',
    category: 'Technical',
    description: 'Server-side JavaScript runtime.',
    aliases: ['node', 'nodejs'],
  },
  {
    name: 'Express',
    slug: 'express',
    category: 'Technical',
    description: 'Minimal HTTP framework for Node.js services.',
    aliases: ['express.js', 'expressjs'],
  },
  {
    name: 'HTML',
    slug: 'html',
    category: 'Technical',
    description: 'Structure and semantics of web pages.',
    aliases: ['html5'],
  },
  {
    name: 'CSS',
    slug: 'css',
    category: 'Technical',
    description: 'Styling, layout, and responsive design.',
    aliases: ['css3'],
  },
  {
    name: 'REST API',
    slug: 'rest-api',
    category: 'Technical',
    description: 'Designing and consuming HTTP interfaces.',
    aliases: ['rest', 'restful', 'restful api'],
  },
  {
    name: 'Git',
    slug: 'git',
    category: 'Technical',
    description: 'Version control and collaborative branching.',
    aliases: ['github', 'gitlab', 'version control'],
  },
  {
    name: 'Testing',
    slug: 'testing',
    category: 'Technical',
    description: 'Automated tests as part of the build.',
    aliases: ['unit testing', 'jest', 'pytest'],
  },
  {
    name: 'Docker',
    slug: 'docker',
    category: 'Technical',
    description: 'Building and running containerised applications.',
    aliases: ['containerization', 'containers'],
  },
  {
    name: 'CI/CD',
    slug: 'ci-cd',
    category: 'Technical',
    description: 'Automated build, test, and deployment pipelines.',
    aliases: ['github actions', 'continuous integration'],
  },
  {
    name: 'Data Cleaning',
    slug: 'data-cleaning',
    category: 'Technical',
    description: 'Fixing missing, duplicated, and inconsistent data.',
    aliases: ['data wrangling', 'data cleansing'],
  },
  {
    name: 'ETL',
    slug: 'etl',
    category: 'Technical',
    description: 'Extract, transform, and load pipelines.',
    aliases: ['data pipelines', 'data pipeline'],
  },
  {
    name: 'Linux',
    slug: 'linux',
    category: 'Technical',
    description: 'Command line and server administration.',
    aliases: ['unix', 'bash'],
  },
  {
    name: 'Responsive Design',
    slug: 'responsive-design',
    category: 'Technical',
    description: 'Layouts that work across phone, tablet, and desktop.',
    aliases: ['mobile first', 'adaptive design'],
  },
  {
    name: 'Accessibility',
    slug: 'accessibility',
    category: 'Technical',
    description: 'Building interfaces usable with keyboard and screen readers.',
    aliases: ['a11y', 'wcag', 'aria'],
  },
  {
    name: 'PostgreSQL',
    slug: 'postgresql',
    category: 'Technical',
    description: 'Relational database administration and querying.',
    aliases: ['postgres', 'psql'],
  },
  {
    name: 'MongoDB',
    slug: 'mongodb',
    category: 'Technical',
    description: 'Document databases and aggregation pipelines.',
    aliases: ['mongo', 'mongoose'],
  },
  {
    name: 'MySQL',
    slug: 'mysql',
    category: 'Technical',
    description: 'Relational database administration and querying.',
    aliases: ['mariadb'],
  },
  {
    name: 'Web Security',
    slug: 'web-security',
    category: 'Technical',
    description: 'Authentication, authorisation, and common web attacks.',
    aliases: ['owasp', 'application security'],
  },
  {
    name: 'Networking',
    slug: 'networking',
    category: 'Technical',
    description: 'How data moves between machines, and the protocols involved.',
    aliases: ['tcp/ip', 'network fundamentals', 'osi model'],
  },
  {
    name: 'Terraform',
    slug: 'terraform',
    category: 'Technical',
    description: 'Declaring cloud infrastructure as code.',
    aliases: ['infrastructure as code', 'iac'],
  },
  {
    name: 'Process Mapping',
    slug: 'process-mapping',
    category: 'Technical',
    description: 'Documenting how work actually flows through a system.',
    aliases: ['workflow analysis', 'bpmn'],
  },
  {
    name: 'Requirements Gathering',
    slug: 'requirements-gathering',
    category: 'Technical',
    description: 'Finding out what a system must do before building it.',
    aliases: ['user research', 'stakeholder interviews'],
  },
  {
    name: 'Business Analysis',
    slug: 'business-analysis',
    category: 'Analytical',
    description: 'Connecting organisational goals to concrete system requirements.',
    aliases: ['business analyst work', 'requirement analysis'],
  },
  {
    name: 'Monitoring',
    slug: 'monitoring',
    category: 'Analytical',
    description: 'Watching a running system and knowing when it degrades.',
    aliases: ['observability', 'alerting'],
  },
  {
    name: 'Content Strategy',
    slug: 'content-strategy',
    category: 'Analytical',
    description: 'Planning content against an audience and a goal.',
    aliases: ['content planning', 'editorial strategy'],
  },
  {
    name: 'Copywriting',
    slug: 'copywriting',
    category: 'Analytical',
    description: 'Writing text that makes a reader act.',
    aliases: ['copy writing', 'persuasive writing'],
  },

  // ─── Analytical ─────────────────────────────────────────────────────────
  {
    name: 'Statistics',
    slug: 'statistics',
    category: 'Analytical',
    description: 'Reasoning about data under uncertainty.',
    aliases: ['stats', 'statistical analysis'],
  },
  {
    name: 'Data Analysis',
    slug: 'data-analysis',
    category: 'Analytical',
    description: 'Turning raw data into a defensible conclusion.',
    aliases: ['analytical reporting'],
  },
  {
    name: 'Probability',
    slug: 'probability',
    category: 'Analytical',
    description: 'Chance, distributions, and inference.',
    aliases: ['probability theory'],
  },
  {
    name: 'Data Modeling',
    slug: 'data-modeling',
    category: 'Analytical',
    description: 'Structuring data for how it will be queried.',
    aliases: ['schema design', 'normalization'],
  },
  {
    name: 'Hypothesis Testing',
    slug: 'hypothesis-testing',
    category: 'Analytical',
    description: 'Deciding whether an observed effect is real.',
    aliases: ['significance testing', 'p-value'],
  },
  {
    name: 'A/B Testing',
    slug: 'ab-testing',
    category: 'Analytical',
    description: 'Comparing two variants with a controlled experiment.',
    aliases: ['split testing', 'experimentation'],
  },
  {
    name: 'Regression',
    slug: 'regression',
    category: 'Analytical',
    description: 'Modelling a numeric outcome from its inputs.',
    aliases: ['linear regression', 'predictive modelling'],
  },
  {
    name: 'Classification',
    slug: 'classification',
    category: 'Analytical',
    description: 'Assigning observations to categories.',
    aliases: ['logistic regression', 'classification models'],
  },
  {
    name: 'Machine Learning',
    slug: 'machine-learning',
    category: 'Analytical',
    description: 'Models that learn patterns from examples.',
    aliases: ['ml', 'scikit-learn', 'sklearn'],
  },
  {
    name: 'Deep Learning',
    slug: 'deep-learning',
    category: 'Analytical',
    description: 'Neural network models and training.',
    aliases: ['neural networks', 'pytorch', 'tensorflow'],
  },
  {
    name: 'Model Evaluation',
    slug: 'model-evaluation',
    category: 'Analytical',
    description: 'Measuring whether a model generalises.',
    aliases: ['cross validation', 'metrics'],
  },
  {
    name: 'Research Design',
    slug: 'research-design',
    category: 'Analytical',
    description: 'Planning a study so its answer is trustworthy.',
    aliases: ['study design', 'methodology'],
  },

  // ─── Tools ──────────────────────────────────────────────────────────────
  {
    name: 'Excel',
    slug: 'excel',
    category: 'Tools',
    description: 'Spreadsheet analysis, formulas, and pivot tables.',
    aliases: ['microsoft excel', 'ms excel', 'spreadsheets', 'google sheets'],
  },
  {
    name: 'Power BI',
    slug: 'power-bi',
    category: 'Tools',
    description: 'Building dashboards and reports.',
    aliases: ['powerbi', 'power bi'],
  },
  {
    name: 'Tableau',
    slug: 'tableau',
    category: 'Tools',
    description: 'Interactive visual analysis and dashboards.',
    aliases: ['tableau desktop'],
  },
  {
    name: 'Data Visualization',
    slug: 'data-visualization',
    category: 'Tools',
    description: 'Choosing and building charts that communicate.',
    aliases: ['data viz', 'dataviz', 'charting'],
  },
  {
    name: 'Pandas',
    slug: 'pandas',
    category: 'Tools',
    description: 'Tabular data manipulation in Python.',
    aliases: ['numpy', 'dataframes'],
  },
  {
    name: 'Figma',
    slug: 'figma',
    category: 'Tools',
    description: 'Interface design and prototyping.',
    aliases: ['figma design'],
  },
  {
    name: 'Threat Detection',
    slug: 'threat-detection',
    category: 'Tools',
    description: 'Identifying malicious activity in logs and alerts.',
    aliases: ['soc analysis', 'incident detection', 'siem'],
  },
  {
    name: 'Shell',
    slug: 'shell',
    category: 'Tools',
    description: 'Command-line scripting and automation.',
    aliases: ['bash scripting', 'zsh'],
  },
  {
    name: 'Google Analytics',
    slug: 'google-analytics',
    category: 'Tools',
    description: 'Measuring website traffic and behaviour.',
    aliases: ['ga4', 'web analytics'],
  },
  {
    name: 'Jira',
    slug: 'jira',
    category: 'Tools',
    description: 'Tracking work and bugs on a team.',
    aliases: ['issue tracking'],
  },
  {
    name: 'SEO',
    slug: 'seo',
    category: 'Tools',
    description: 'Improving how a site appears in search results.',
    aliases: ['search engine optimisation', 'search engine optimization', 'technical seo'],
  },
  {
    name: 'Social Media',
    slug: 'social-media',
    category: 'Tools',
    description: 'Running a brand presence across social platforms.',
    aliases: ['social marketing', 'community management'],
  },
  {
    name: 'Paid Advertising',
    slug: 'paid-advertising',
    category: 'Tools',
    description: 'Running paid search and social campaigns.',
    aliases: ['google ads', 'facebook ads', 'ppc'],
  },
  {
    name: 'Project Management',
    slug: 'project-management',
    category: 'Tools',
    description: 'Planning and tracking delivery of work.',
    aliases: ['scrum', 'agile', 'kanban'],
  },
  {
    name: 'UI Design',
    slug: 'ui-design',
    category: 'Tools',
    description: 'Designing interface layout and visual hierarchy.',
    aliases: ['interface design', 'visual design'],
  },
  {
    name: 'UX Design',
    slug: 'ux-design',
    category: 'Tools',
    description: 'Designing how a product feels to use.',
    aliases: ['user experience', 'usability'],
  },
  {
    name: 'Prototyping',
    slug: 'prototyping',
    category: 'Tools',
    description: 'Building clickable versions of a design before it is built.',
    aliases: ['wireframing', 'mockups', 'lo-fi prototype'],
  },
  {
    name: 'Web Performance',
    slug: 'web-performance',
    category: 'Tools',
    description: 'Making pages load quickly on slow connections.',
    aliases: ['core web vitals', 'lighthouse', 'page speed'],
  },
  {
    name: 'Slack',
    slug: 'slack',
    category: 'Tools',
    description: 'Team communication in a working project.',
    aliases: ['team chat'],
  },
  {
    name: 'Notion',
    slug: 'notion',
    category: 'Tools',
    description: 'Notes, specs, and lightweight project docs.',
    aliases: ['documentation'],
  },
  {
    name: 'Google Sheets',
    slug: 'google-sheets',
    category: 'Tools',
    description: 'Collaborative online spreadsheets.',
    aliases: ['sheets'],
  },
  {
    name: 'Postman',
    slug: 'postman',
    category: 'Tools',
    description: 'Exploring and testing HTTP APIs.',
    aliases: ['api client', 'insomnia'],
  },
  {
    name: 'GitHub',
    slug: 'github',
    category: 'Tools',
    description: 'Hosting code and managing issues and pull requests.',
    aliases: ['github.com'],
  },
  {
    name: 'Kubernetes',
    slug: 'kubernetes',
    category: 'Tools',
    description: 'Orchestrating containerised workloads.',
    aliases: ['k8s'],
  },
  {
    name: 'AWS',
    slug: 'aws',
    category: 'Tools',
    description: 'Cloud compute, storage, and services.',
    aliases: ['amazon web services'],
  },
  {
    name: 'Linux CLI',
    slug: 'linux-cli',
    category: 'Tools',
    description: 'Command line productivity.',
    aliases: ['shell', 'terminal', 'bash'],
  },

  // ─── Soft skills ────────────────────────────────────────────────────────
  {
    name: 'Communication',
    slug: 'communication',
    category: 'Soft skills',
    description: 'Explaining work clearly to non-specialists.',
    aliases: ['communication skills', 'presenting', 'written communication'],
  },
  {
    name: 'Teamwork',
    slug: 'teamwork',
    category: 'Soft skills',
    description: 'Working well with people who are not you.',
    aliases: ['collaboration', 'cross-functional'],
  },
  {
    name: 'Problem Solving',
    slug: 'problem-solving',
    category: 'Soft skills',
    description: 'Breaking an unclear problem into solvable parts.',
    aliases: ['troubleshooting', 'debugging'],
  },
  {
    name: 'Critical Thinking',
    slug: 'critical-thinking',
    category: 'Soft skills',
    description: 'Evaluating evidence before accepting a claim.',
    aliases: ['reasoning', 'analytical thinking'],
  },
  {
    name: 'Leadership',
    slug: 'leadership',
    category: 'Soft skills',
    description: 'Taking responsibility for an outcome.',
    aliases: ['team lead', 'mentoring'],
  },
  {
    name: 'Time Management',
    slug: 'time-management',
    category: 'Soft skills',
    description: 'Prioritising and delivering against a deadline.',
    aliases: ['prioritization', 'prioritisation'],
  },
  {
    name: 'Attention to Detail',
    slug: 'attention-to-detail',
    category: 'Soft skills',
    description: 'Catching errors that others miss.',
    aliases: ['meticulous', 'detail-oriented'],
  },
  {
    name: 'Adaptability',
    slug: 'adaptability',
    category: 'Soft skills',
    description: 'Learning quickly when the plan changes.',
    aliases: ['flexibility', 'quick learner'],
  },
  {
    name: 'Presentation',
    slug: 'presentation',
    category: 'Soft skills',
    description: 'Delivering a talk or demo that lands.',
    aliases: ['public speaking', 'storytelling'],
  },
  {
    name: 'Stakeholder Management',
    slug: 'stakeholder-management',
    category: 'Soft skills',
    description: 'Aligning people who do not report to you.',
    aliases: ['stakeholder communication'],
  },
  {
    name: 'Technical Writing',
    slug: 'technical-writing',
    category: 'Soft skills',
    description: 'Explaining a system in writing others can follow.',
    aliases: ['documentation writing'],
  },
];
