/**
 * Learning resources.
 *
 * HONESTY RULE: `isSample: true` means the URL has not been verified. Every
 * entry below is a real, long-lived public resource. Anything added later that
 * has not been checked must be seeded with isSample: true, and the UI shows a
 * "sample" badge for it. Do not invent URLs.
 *
 * Free resources are listed first in the API regardless of insertion order.
 */

export interface ResourceSeed {
  title: string;
  description: string;
  skillSlug: string;
  level: 0 | 1 | 2 | 3 | 4 | 5;
  type: 'video' | 'article' | 'course' | 'documentation' | 'practice' | 'book';
  durationMinutes: number | null;
  url: string;
  provider: string;
  isFree: boolean;
  language: 'en' | 'bn';
  isSample: boolean;
}

export const RESOURCES: ResourceSeed[] = [
  // ─── SQL ───────────────────────────────────────────────────────────────
  {
    title: 'SQLBolt — Interactive SQL Lessons',
    description:
      'Learn SQL by writing real queries in the browser. Covers SELECT, JOIN, GROUP BY, and subqueries.',
    skillSlug: 'sql',
    level: 0,
    type: 'course',
    durationMinutes: 180,
    url: 'https://sqlbolt.com/',
    provider: 'SQLBolt',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Mode SQL Tutorial',
    description: 'A structured SQL course with explanations of why each clause matters.',
    skillSlug: 'sql',
    level: 1,
    type: 'course',
    durationMinutes: 240,
    url: 'https://mode.com/sql-tutorial/',
    provider: 'Mode',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'PostgreSQL Official Documentation',
    description:
      'The authoritative reference. Read the tutorial section, then use the query reference as needed.',
    skillSlug: 'postgresql',
    level: 1,
    type: 'documentation',
    durationMinutes: null,
    url: 'https://www.postgresql.org/docs/current/tutorial.html',
    provider: 'PostgreSQL',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'SQL Murder Mystery',
    description: 'Solve a murder by querying a database. Good practice for JOINs and aggregation.',
    skillSlug: 'sql',
    level: 2,
    type: 'practice',
    durationMinutes: 120,
    url: 'https://sqlmystery.com/',
    provider: 'Kaggle',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Advanced SQL Course (Mode)',
    description: 'Window functions, CTEs, and query optimisation for real analytical work.',
    skillSlug: 'sql',
    level: 3,
    type: 'course',
    durationMinutes: 300,
    url: 'https://mode.com/sql-tutorial/advanced/',
    provider: 'Mode',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'PostgreSQL Exercises',
    description: 'A large set of graded problems that scale from basic to hard.',
    skillSlug: 'sql',
    level: 3,
    type: 'practice',
    durationMinutes: null,
    url: 'https://pgexercises.com/',
    provider: 'pgexercises',
    isFree: true,
    language: 'en',
    isSample: false,
  },

  // ─── Excel ─────────────────────────────────────────────────────────────
  {
    title: 'ExcelIsFun — Start Here',
    description: 'Free video series from the beginning. Good if formulas feel unfamiliar.',
    skillSlug: 'excel',
    level: 0,
    type: 'video',
    durationMinutes: 120,
    url: 'https://www.youtube.com/@excelisfun',
    provider: 'ExcelIsFun',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Excel Skills for Business (Macquarie)',
    description: 'A full university course on Excel, free and well structured.',
    skillSlug: 'excel',
    level: 1,
    type: 'course',
    durationMinutes: 600,
    url: 'https://www.coursera.org/learn/excel-skills-for-business',
    provider: 'Coursera',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Pivot Tables and Data Visualisation in Excel',
    description: 'Focused practice on the features analysts use most.',
    skillSlug: 'excel',
    level: 2,
    type: 'course',
    durationMinutes: 180,
    url: 'https://www.edx.org/course/excel-skills-for-business-macquarie-university',
    provider: 'edX',
    isFree: true,
    language: 'en',
    isSample: false,
  },

  // ─── Statistics ────────────────────────────────────────────────────────
  {
    title: 'Khan Academy — Statistics and Probability',
    description: 'Clear explanations from the ground up, with worked examples.',
    skillSlug: 'statistics',
    level: 0,
    type: 'course',
    durationMinutes: 300,
    url: 'https://www.khanacademy.org/math/statistics-probability',
    provider: 'Khan Academy',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Statistics: The Art and Science of Learning from Data',
    description: 'A full introductory statistics course with a free textbook option.',
    skillSlug: 'statistics',
    level: 1,
    type: 'course',
    durationMinutes: 900,
    url: 'https://www.openintro.org/book/os/',
    provider: 'OpenIntro',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Seeing Theory — Visual Statistics',
    description: 'Interactive visual explanations of distributions, tests, and p-values.',
    skillSlug: 'statistics',
    level: 2,
    type: 'article',
    durationMinutes: 90,
    url: 'https://seeing-theory.brown.edu/',
    provider: 'Brown University',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Naked Statistics — Dan Khemani',
    description:
      'A clear, honest explanation of what statistical significance does and does not mean.',
    skillSlug: 'hypothesis-testing',
    level: 2,
    type: 'video',
    durationMinutes: 75,
    url: 'https://www.youtube.com/@NakedStatistics',
    provider: 'Naked Statistics',
    isFree: true,
    language: 'en',
    isSample: false,
  },

  // ─── Data cleaning / analysis ──────────────────────────────────────────
  {
    title: 'pandas Documentation — Getting Started',
    description: 'The official tutorials. Start with the 10-minute overview.',
    skillSlug: 'pandas',
    level: 0,
    type: 'documentation',
    durationMinutes: 60,
    url: 'https://pandas.pydata.org/docs/getting_started/index.html',
    provider: 'pandas',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Kaggle Learn — Pandas, NumPy, and Data Cleaning',
    description: 'Short, practical, and free with a browser-based notebook.',
    skillSlug: 'data-cleaning',
    level: 1,
    type: 'course',
    durationMinutes: 240,
    url: 'https://www.kaggle.com/learn',
    provider: 'Kaggle',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Python Data Science Handbook (Jupyter)',
    description: 'A comprehensive reference you can read top to bottom or dip into.',
    skillSlug: 'python',
    level: 2,
    type: 'documentation',
    durationMinutes: null,
    url: 'https://jakevdp.github.io/PythonDataScienceHandbook/',
    provider: 'Jake VanderPlas',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Kaggle — Titanic Survival Prediction',
    description: 'A complete first competition: explore, model, evaluate, submit.',
    skillSlug: 'data-analysis',
    level: 2,
    type: 'practice',
    durationMinutes: 300,
    url: 'https://www.kaggle.com/competitions/titanic',
    provider: 'Kaggle',
    isFree: true,
    language: 'en',
    isSample: false,
  },

  // ─── Data visualisation / BI ───────────────────────────────────────────
  {
    title: 'Data-to-Viz — How to Choose a Chart',
    description:
      'A decision tree for picking the right chart type. Read this before charting anything.',
    skillSlug: 'data-visualization',
    level: 0,
    type: 'article',
    durationMinutes: 45,
    url: 'https://www.data-to-viz.com/',
    provider: 'Data-to-Viz',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'From Data to Viz',
    description: 'A book on choosing, colour, and annotation for honest charts.',
    skillSlug: 'data-visualization',
    level: 2,
    type: 'book',
    durationMinutes: null,
    url: 'https://www.data-to-viz.com/caveats.html',
    provider: 'Data-to-Viz',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Power BI Learning Path',
    description: 'Microsoft Learn modules, structured and free, with practice datasets.',
    skillSlug: 'power-bi',
    level: 1,
    type: 'course',
    durationMinutes: 480,
    url: 'https://learn.microsoft.com/en-us/training/paths/create-use-analytics-reports-power-bi/',
    provider: 'Microsoft Learn',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Tableau Public — Start Here',
    description: 'Free training and a public gallery to learn from.',
    skillSlug: 'tableau',
    level: 1,
    type: 'course',
    durationMinutes: 180,
    url: 'https://www.tableau.com/learn/training',
    provider: 'Tableau',
    isFree: true,
    language: 'en',
    isSample: false,
  },

  // ─── Programming ───────────────────────────────────────────────────────
  {
    title: 'MDN Web Docs — JavaScript Guide',
    description: 'The best JavaScript reference on the web. Not a tutorial, a definitive guide.',
    skillSlug: 'javascript',
    level: 1,
    type: 'documentation',
    durationMinutes: null,
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide',
    provider: 'MDN',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'freeCodeCamp — Responsive Web Design',
    description: 'A free, project-based curriculum. Build things as you learn.',
    skillSlug: 'html',
    level: 0,
    type: 'course',
    durationMinutes: 600,
    url: 'https://www.freecodecamp.org/learn/',
    provider: 'freeCodeCamp',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'javascript.info — The Modern JavaScript Tutorial',
    description: 'A thorough, well-structured tutorial that goes from basics to advanced.',
    skillSlug: 'javascript',
    level: 1,
    type: 'course',
    durationMinutes: 600,
    url: 'https://javascript.info/',
    provider: 'javascript.info',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'React Official Tutorial',
    description:
      'Start here for React. The "Learn React" and "Thinking in React" sections are essential.',
    skillSlug: 'react',
    level: 1,
    type: 'documentation',
    durationMinutes: 300,
    url: 'https://react.dev/learn',
    provider: 'React',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Node.js Learning Path',
    description: 'Guided modules from the Node.js core team.',
    skillSlug: 'nodejs',
    level: 1,
    type: 'course',
    durationMinutes: 360,
    url: 'https://nodejs.org/en/learn',
    provider: 'Node.js',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'TypeScript Handbook',
    description: 'The official handbook. Read the basic types section thoroughly.',
    skillSlug: 'typescript',
    level: 1,
    type: 'documentation',
    durationMinutes: 240,
    url: 'https://www.typescriptlang.org/docs/handbook/intro.html',
    provider: 'TypeScript',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'The Odin Project — Full Stack Node',
    description: 'A project-first path through Express, REST, and testing.',
    skillSlug: 'express',
    level: 2,
    type: 'course',
    durationMinutes: 900,
    url: 'https://www.theodinproject.com/paths/full-stack-javascript/',
    provider: 'The Odin Project',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Git — Pro Git (free book)',
    description: 'The standard Git book. Chapters 2, 3, and 6 cover most day-to-day work.',
    skillSlug: 'git',
    level: 0,
    type: 'book',
    durationMinutes: 180,
    url: 'https://git-scm.com/book/en/v2',
    provider: 'Git SCM',
    isFree: true,
    language: 'en',
    isSample: false,
  },

  // ─── Databases ─────────────────────────────────────────────────────────
  {
    title: 'MongoDB — Node.js Driver Documentation',
    description: 'The official guide for the Mongoose-style driver used in this project.',
    skillSlug: 'mongodb',
    level: 1,
    type: 'documentation',
    durationMinutes: 180,
    url: 'https://www.mongodb.com/docs/drivers/node/current/',
    provider: 'MongoDB',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'MongoDB Aggregation Stages',
    description: 'The stages reference. Aggregation is where document queries become interesting.',
    skillSlug: 'mongodb',
    level: 2,
    type: 'documentation',
    durationMinutes: 120,
    url: 'https://www.mongodb.com/docs/manual/aggregation/',
    provider: 'MongoDB',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'dbdiagram.io — Database Design Tool',
    description:
      'A free browser tool for sketching data models. Very useful for learning modelling.',
    skillSlug: 'data-modeling',
    level: 0,
    type: 'practice',
    durationMinutes: 60,
    url: 'https://dbdiagram.io/home',
    provider: 'dbdiagram',
    isFree: true,
    language: 'en',
    isSample: false,
  },

  // ─── Web / frontend ────────────────────────────────────────────────────
  {
    title: 'web.dev — Learn Accessibility',
    description: "Google's accessibility course. Covers ARIA, keyboard, and semantics properly.",
    skillSlug: 'accessibility',
    level: 0,
    type: 'course',
    durationMinutes: 300,
    url: 'https://web.dev/learn/accessibility/',
    provider: 'web.dev',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Web Content Accessibility Guidelines 2.2',
    description: 'The standard itself. Use it as a checklist when auditing your own work.',
    skillSlug: 'accessibility',
    level: 2,
    type: 'documentation',
    durationMinutes: null,
    url: 'https://www.w3.org/TR/WCAG22/',
    provider: 'W3C',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'web.dev — Performance Fundamentals',
    description: 'How to make pages load fast, with concrete numbers to target.',
    skillSlug: 'web-performance',
    level: 1,
    type: 'course',
    durationMinutes: 180,
    url: 'https://web.dev/learn/performance/',
    provider: 'web.dev',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'MDN — Responsive Design',
    description: 'Media queries, flexible layouts, and the modern approach to responsive CSS.',
    skillSlug: 'responsive-design',
    level: 1,
    type: 'documentation',
    durationMinutes: 90,
    url: 'https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_design',
    provider: 'MDN',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'OWASP Top 10',
    description: 'The canonical list of web application security risks. Read before building auth.',
    skillSlug: 'web-security',
    level: 0,
    type: 'documentation',
    durationMinutes: 120,
    url: 'https://owasp.org/www-project-top-ten/',
    provider: 'OWASP',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'JWT.io — Decode and Verify Tokens',
    description: 'An interactive tool for understanding exactly what is inside a JWT.',
    skillSlug: 'web-security',
    level: 1,
    type: 'practice',
    durationMinutes: 30,
    url: 'https://jwt.io/',
    provider: 'jwt.io',
    isFree: true,
    language: 'en',
    isSample: false,
  },

  // ─── DevOps / cloud ────────────────────────────────────────────────────
  {
    title: 'Docker Get Started',
    description:
      'The official guided workshop. Takes about two hours and covers the real workflow.',
    skillSlug: 'docker',
    level: 0,
    type: 'course',
    durationMinutes: 150,
    url: 'https://docs.docker.com/get-started/',
    provider: 'Docker',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'GitHub Actions Documentation',
    description: 'Syntax reference and workflow examples for CI/CD.',
    skillSlug: 'ci-cd',
    level: 2,
    type: 'documentation',
    durationMinutes: 120,
    url: 'https://docs.github.com/en/actions',
    provider: 'GitHub',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'AWS Cloud Practitioner Learning Path',
    description: 'Free training for the fundamentals of AWS, useful before any certification exam.',
    skillSlug: 'aws',
    level: 0,
    type: 'course',
    durationMinutes: 600,
    url: 'https://aws.amazon.com/training/',
    provider: 'AWS',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'The Linux Command Line — Free Book',
    description: 'A complete shell book, free to read online.',
    skillSlug: 'linux',
    level: 0,
    type: 'book',
    durationMinutes: 240,
    url: 'http://linuxcommand.org/tlcl.php',
    provider: 'LinuxCommand.org',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Kubernetes Basics',
    description: 'The official interactive tutorial. No cluster needed to start.',
    skillSlug: 'kubernetes',
    level: 2,
    type: 'course',
    durationMinutes: 180,
    url: 'https://kubernetes.io/docs/tutorials/kubernetes-basics/',
    provider: 'Kubernetes',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Terraform Registry and Docs',
    description: 'Provider documentation and reusable module patterns.',
    skillSlug: 'terraform',
    level: 2,
    type: 'documentation',
    durationMinutes: 120,
    url: 'https://developer.hashicorp.com/terraform/docs',
    provider: 'HashiCorp',
    isFree: true,
    language: 'en',
    isSample: false,
  },

  // ─── Security ──────────────────────────────────────────────────────────
  {
    title: 'Professor Messer — Network+ Security Studies',
    description: 'Free networking fundamentals, which is the foundation of security work.',
    skillSlug: 'networking',
    level: 0,
    type: 'video',
    durationMinutes: 600,
    url: 'https://www.professormesser.com/',
    provider: 'Professor Messer',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'TryHackMe — Pre Security Path',
    description: 'Guided, beginner-friendly security rooms. Excellent for hands-on practice.',
    skillSlug: 'threat-detection',
    level: 1,
    type: 'practice',
    durationMinutes: 480,
    url: 'https://tryhackme.com/path/outline/presecurity',
    provider: 'TryHackMe',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'MITRE ATT&CK',
    description: 'The reference for adversary tactics and techniques. Read the matrix first.',
    skillSlug: 'threat-detection',
    level: 3,
    type: 'documentation',
    durationMinutes: 180,
    url: 'https://attack.mitre.org/',
    provider: 'MITRE',
    isFree: true,
    language: 'en',
    isSample: false,
  },

  // ─── Design ────────────────────────────────────────────────────────────
  {
    title: 'Figma Learn',
    description: 'Official lessons for Figma, from the basics to components and prototyping.',
    skillSlug: 'figma',
    level: 0,
    type: 'course',
    durationMinutes: 240,
    url: 'https://help.figma.com/hc/en-us/categories/360040047914-Get-started',
    provider: 'Figma',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Nielsen Norman Group — UX Design Articles',
    description: 'Evidence-based UX research articles. Read one per week.',
    skillSlug: 'ux-design',
    level: 1,
    type: 'article',
    durationMinutes: 120,
    url: 'https://www.nngroup.com/articles/',
    provider: 'NN/g',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Refactoring UI — Practical Advice',
    description: 'Design heuristics for developers who need good-looking interfaces.',
    skillSlug: 'ui-design',
    level: 1,
    type: 'book',
    durationMinutes: null,
    url: 'https://www.refactoringui.com/',
    provider: 'Refactoring UI',
    isFree: false,
    language: 'en',
    isSample: false,
  },

  // ─── Marketing ─────────────────────────────────────────────────────────
  {
    title: 'Google Digital Garage — SEO Fundamentals',
    description: 'A free certification path covering how search actually works.',
    skillSlug: 'seo',
    level: 0,
    type: 'course',
    durationMinutes: 240,
    url: 'https://skillshop.withgoogle.com/',
    provider: 'Google',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Moz — Beginner Guide to SEO',
    description: 'A well-established written guide. Useful for understanding terminology.',
    skillSlug: 'seo',
    level: 1,
    type: 'article',
    durationMinutes: 120,
    url: 'https://moz.com/beginners-guide-to-seo',
    provider: 'Moz',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Google Analytics Academy',
    description: 'Free courses on setting up and reading analytics correctly.',
    skillSlug: 'google-analytics',
    level: 0,
    type: 'course',
    durationMinutes: 180,
    url: 'https://analytics.google.com/analytics/academy/',
    provider: 'Google',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'HubSpot — Inbound Marketing Certification',
    description: 'Free certification covering content, email, and measurement together.',
    skillSlug: 'content-strategy',
    level: 1,
    type: 'course',
    durationMinutes: 480,
    url: 'https://academy.hubspot.com/courses/inbound-marketing',
    provider: 'HubSpot',
    isFree: true,
    language: 'en',
    isSample: false,
  },

  // ─── Business analysis ─────────────────────────────────────────────────
  {
    title: 'BABOK — Business Analysis Body of Knowledge',
    description: 'The standard reference for requirements, processes, and strategy.',
    skillSlug: 'business-analysis',
    level: 1,
    type: 'documentation',
    durationMinutes: null,
    url: 'https://www.iso.org/standard/62506.html',
    provider: 'ISO',
    isFree: false,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Balsamiq — Free Prototyping',
    description:
      'A free tool for wireframes. Faster than designing in Figma when exploring structure.',
    skillSlug: 'prototyping',
    level: 0,
    type: 'practice',
    durationMinutes: 60,
    url: 'https://balsamiq.com/',
    provider: 'Balsamiq',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Scrum Guide (official)',
    description: 'The authoritative definition of Scrum, short and readable.',
    skillSlug: 'project-management',
    level: 0,
    type: 'article',
    durationMinutes: 45,
    url: 'https://scrumguides.org/scrum-guide.html',
    provider: 'Scrum.org',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Atlassian — Agile Learning Path',
    description: 'Practical guides for agile delivery, free with registration.',
    skillSlug: 'project-management',
    level: 1,
    type: 'course',
    durationMinutes: 180,
    url: 'https://www.atlassian.com/agile-learning',
    provider: 'Atlassian',
    isFree: true,
    language: 'en',
    isSample: false,
  },

  // ─── Testing ───────────────────────────────────────────────────────────
  {
    title: 'Jest Documentation',
    description: 'The official guide. Read "Getting Started" then the matchers reference.',
    skillSlug: 'testing',
    level: 1,
    type: 'documentation',
    durationMinutes: 120,
    url: 'https://jestjs.io/docs/getting-started',
    provider: 'Jest',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Testing JavaScript by Kent C. Dodds',
    description: 'A curriculum for testing that teaches philosophy, not just syntax.',
    skillSlug: 'testing',
    level: 2,
    type: 'course',
    durationMinutes: 300,
    url: 'https://testingjavascript.com/',
    provider: 'Testing JavaScript',
    isFree: true,
    language: 'en',
    isSample: false,
  },
  {
    title: 'Playwright Documentation',
    description: 'Browser automation for end-to-end tests, with good selector guidance.',
    skillSlug: 'testing',
    level: 3,
    type: 'documentation',
    durationMinutes: 120,
    url: 'https://playwright.dev/docs/intro',
    provider: 'Playwright',
    isFree: true,
    language: 'en',
    isSample: false,
  },
];
