/**
 * Career definitions and career-skill mappings.
 *
 * No salary figures and no employment-probability claims appear anywhere in
 * this file, by design. Each career states what the role requires, not what it
 * pays or how likely a hire is.
 */

export interface CareerSeed {
  slug: string;
  name: string;
  category:
    | 'Data & AI'
    | 'Software'
    | 'Design'
    | 'Security'
    | 'Cloud & Infrastructure'
    | 'Business & Marketing';
  summary: string;
  description: string;
  responsibilities: string[];
  typicalProjects: { title: string; description: string }[];
}

export interface CareerSkillSeed {
  careerSlug: string;
  skillSlug: string;
  requiredLevel: 0 | 1 | 2 | 3 | 4 | 5;
  importance: 'high' | 'medium' | 'low';
  isCore?: boolean;
  estimatedEffortHours: number;
  prerequisiteSkillSlugs?: string[];
}

export const CAREERS: CareerSeed[] = [
  {
    slug: 'data-analyst',
    name: 'Data Analyst',
    category: 'Data & AI',
    summary: 'Turn raw data into findings that someone can act on.',
    description:
      'A data analyst sits between the data and the people who make decisions. You clean and structure data, write queries to answer a real question, build the reporting others rely on, and explain what the numbers mean in plain language. The work is less about advanced mathematics than about being careful, curious, and able to communicate.',
    responsibilities: [
      'Write SQL queries to extract and combine data from relational databases',
      'Clean and validate data so downstream numbers are trustworthy',
      'Build dashboards and recurring reports for non-technical stakeholders',
      'Design analyses that answer a specific business question, not a vague one',
      'Document methodology so another analyst can reproduce the result',
    ],
    typicalProjects: [
      {
        title: 'Public transport ridership dashboard',
        description: 'Analyse a city bus dataset and build a dashboard of route usage over time.',
      },
      {
        title: 'E-commerce retention analysis',
        description: 'Find why customers stop purchasing and quantify the effect of each factor.',
      },
    ],
  },
  {
    slug: 'data-scientist',
    name: 'Data Scientist',
    category: 'Data & AI',
    summary: 'Build and evaluate models that generalise to new data.',
    description:
      'A data scientist formulates questions as statistical or machine-learning problems, prepares data, trains models, and measures whether their performance would hold on data they have never seen. Strong statistical reasoning matters more than knowing a long list of algorithms.',
    responsibilities: [
      'Frame a business problem as a modelling problem with a measurable outcome',
      'Prepare datasets, handle leakage, and split data correctly',
      'Select and tune models appropriate to the data type',
      'Evaluate with metrics that reflect real deployment conditions',
      'Explain model behaviour and limitations to non-specialists',
    ],
    typicalProjects: [
      {
        title: 'House price prediction model',
        description:
          'Build and honestly evaluate a regression model, including what it cannot predict.',
      },
      {
        title: 'Customer churn classifier',
        description: 'Predict churn and examine which features actually drive the decision.',
      },
    ],
  },
  {
    slug: 'machine-learning-engineer',
    name: 'ML Engineer',
    category: 'Data & AI',
    summary: 'Put models into production and keep them running.',
    description:
      'An ML engineer focuses on the systems around the model: data pipelines, training orchestration, serving latency, monitoring, and retraining. The model is one component of a larger system that has to stay reliable.',
    responsibilities: [
      'Build and maintain data pipelines feeding training and serving',
      'Containerise and deploy models with appropriate latency and cost',
      'Monitor models for drift and data-quality regressions in production',
      'Version models, datasets, and features together',
      'Design serving APIs that other services can call reliably',
    ],
    typicalProjects: [
      {
        title: 'Sentiment analysis service',
        description:
          'Ship a small text classifier behind an API with monitoring and a fallback path.',
      },
      {
        title: 'Recommendation pipeline',
        description:
          'Build an offline training job and an online lookup service for recommendations.',
      },
    ],
  },
  {
    slug: 'software-engineer',
    name: 'Software Engineer',
    category: 'Software',
    summary: 'Design, build, test, and maintain software systems.',
    description:
      "Software engineers turn a requirement into working, maintainable code. You design data structures, write tests, review other people's code, and keep systems understandable as they grow. Depth in one language beats shallow familiarity in five.",
    responsibilities: [
      'Design data models and service boundaries that stay maintainable',
      'Write automated tests that let others change code safely',
      'Review code and give feedback that is specific and actionable',
      'Debug systematically rather than guessing at fixes',
      'Document decisions so future readers know why',
    ],
    typicalProjects: [
      {
        title: 'REST API with a real database',
        description: 'Build an API with validation, error handling, and a test suite.',
      },
      {
        title: 'Task management web app',
        description: 'Ship a full-stack app with authentication and role-based access.',
      },
    ],
  },
  {
    slug: 'web-developer',
    name: 'Web Developer',
    category: 'Software',
    summary: 'Build the interfaces people actually use.',
    description:
      'A web developer builds the front end and the services behind it. Modern work requires accessibility and performance to be designed in from the start, not patched on later, and comfortable JavaScript across the stack.',
    responsibilities: [
      'Build responsive, accessible interfaces from design intent',
      'Manage client state, data fetching, and error and loading states',
      'Work effectively with designers and back-end engineers',
      'Improve load performance and bundle size',
      'Ensure the site works on low-end mobile devices',
    ],
    typicalProjects: [
      {
        title: 'Accessible dashboard',
        description:
          'Build a data dashboard that is fully usable with a keyboard and screen reader.',
      },
      {
        title: 'E-commerce product page',
        description: 'Build a fast, responsive product page with working filters and a cart.',
      },
    ],
  },
  {
    slug: 'cybersecurity-analyst',
    name: 'Cybersecurity Analyst',
    category: 'Security',
    summary: 'Detect, investigate, and help prevent security incidents.',
    description:
      'A security analyst monitors systems for suspicious activity, investigates alerts to separate real incidents from noise, and recommends concrete remediations. Reporting a finding is only half the job; the other half is explaining what to do about it.',
    responsibilities: [
      'Monitor logs and alerts for indicators of compromise',
      'Triage and investigate alerts to find genuine incidents',
      'Recommend and verify remediations',
      'Write clear incident documentation and timelines',
      'Apply security controls to systems and review access permissions',
    ],
    typicalProjects: [
      {
        title: 'Home lab detection project',
        description: 'Build a small lab, generate attack traffic, and write detections for it.',
      },
      {
        title: 'Log analysis exercise',
        description: 'Practise identifying a real intrusion inside noisy, mostly-benign logs.',
      },
    ],
  },
  {
    slug: 'ui-ux-designer',
    name: 'UI/UX Designer',
    category: 'Design',
    summary: 'Design interfaces people can understand and use.',
    description:
      'A UI/UX designer works out what a product should do before it is built. That means research, information architecture, wireframes, prototypes, and usability testing. Craft in Figma matters, but the reasoning behind a decision matters more.',
    responsibilities: [
      'Research users and turn findings into design requirements',
      'Create wireframes, flows, and interactive prototypes',
      'Run usability tests and iterate on what the evidence shows',
      'Maintain a design system that keeps the product consistent',
      'Design to accessibility standards, not just visual preference',
    ],
    typicalProjects: [
      {
        title: 'Redesign a government form',
        description: 'Simplify a real public-service form and test whether people can complete it.',
      },
      {
        title: 'Design system starter',
        description: 'Define components, tokens, and states for a small product.',
      },
    ],
  },
  {
    slug: 'cloud-engineer',
    name: 'Cloud Engineer',
    category: 'Cloud & Infrastructure',
    summary: 'Run and scale infrastructure as code.',
    description:
      'A cloud engineer builds and operates the infrastructure an application runs on. You define infrastructure as code, automate provisioning, design for failure, and keep cost and security in view at the same time.',
    responsibilities: [
      'Define infrastructure as code and automate provisioning',
      'Design networks, storage, and compute that scale with demand',
      'Automate deployment, monitoring, and alerting',
      'Manage cost and right-size resources',
      'Apply least-privilege access and network security controls',
    ],
    typicalProjects: [
      {
        title: 'Containerised service on a cloud VM',
        description: 'Deploy a service with a reverse proxy, TLS, and automated backups.',
      },
      {
        title: 'Infrastructure as code migration',
        description: 'Move a manually built environment to reproducible code.',
      },
    ],
  },
  {
    slug: 'digital-marketing-specialist',
    name: 'Digital Marketing Specialist',
    category: 'Business & Marketing',
    summary: 'Plan and run measurable campaigns that reach an audience.',
    description:
      'A digital marketing specialist plans campaigns, chooses channels based on where the audience actually is, and measures what happened. Attributing results honestly is a core skill, not an optional one.',
    responsibilities: [
      'Plan campaigns tied to a defined audience and measurable objective',
      'Run and optimise paid and organic channels',
      'Measure performance with correct attribution',
      'Test creative and messaging systematically',
      'Report results honestly, including what did not work',
    ],
    typicalProjects: [
      {
        title: 'Local business campaign',
        description: 'Run a small campaign for a real local business and report honest results.',
      },
      {
        title: 'SEO content audit',
        description: 'Audit a site and prioritise fixes by expected impact and effort.',
      },
    ],
  },
  {
    slug: 'business-analyst',
    name: 'Business Analyst',
    category: 'Business & Marketing',
    summary: 'Turn business needs into clear, testable requirements.',
    description:
      'A business analyst works between stakeholders and delivery teams. You elicit what people actually need, document it precisely, model the process, and define how success will be measured before engineering starts.',
    responsibilities: [
      'Elicit and clarify requirements from non-technical stakeholders',
      'Model current and future business processes',
      'Write precise acceptance criteria',
      'Identify and quantify the benefit of a proposed change',
      'Facilitate decisions and document trade-offs',
    ],
    typicalProjects: [
      {
        title: 'Process improvement case study',
        description:
          'Map a real process, find the bottleneck, and quantify a proposed improvement.',
      },
      {
        title: 'Requirements specification',
        description:
          'Write a complete specification for a small system, including acceptance criteria.',
      },
    ],
  },
];

export const CAREER_SKILLS: CareerSkillSeed[] = [
  // ─── Data Analyst ──────────────────────────────────────────────────────
  {
    careerSlug: 'data-analyst',
    skillSlug: 'sql',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 40,
  },
  {
    careerSlug: 'data-analyst',
    skillSlug: 'excel',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'data-analyst',
    skillSlug: 'statistics',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 30,
    prerequisiteSkillSlugs: [],
  },
  {
    careerSlug: 'data-analyst',
    skillSlug: 'data-cleaning',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'data-analyst',
    skillSlug: 'data-visualization',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'data-analyst',
    skillSlug: 'power-bi',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 20,
    prerequisiteSkillSlugs: ['sql', 'data-visualization'],
  },
  {
    careerSlug: 'data-analyst',
    skillSlug: 'python',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'data-analyst',
    skillSlug: 'pandas',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 15,
    prerequisiteSkillSlugs: ['python'],
  },
  {
    careerSlug: 'data-analyst',
    skillSlug: 'data-modeling',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'data-analyst',
    skillSlug: 'communication',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 10,
  },
  {
    careerSlug: 'data-analyst',
    skillSlug: 'problem-solving',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 10,
  },
  {
    careerSlug: 'data-analyst',
    skillSlug: 'critical-thinking',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 10,
  },
  {
    careerSlug: 'data-analyst',
    skillSlug: 'tableau',
    requiredLevel: 2,
    importance: 'low',
    estimatedEffortHours: 15,
  },

  // ─── Data Scientist ────────────────────────────────────────────────────
  {
    careerSlug: 'data-scientist',
    skillSlug: 'python',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 50,
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'statistics',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 50,
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'probability',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 25,
    prerequisiteSkillSlugs: ['statistics'],
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'machine-learning',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 60,
    prerequisiteSkillSlugs: ['python', 'statistics'],
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'pandas',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 15,
    prerequisiteSkillSlugs: ['python'],
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'model-evaluation',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 20,
    prerequisiteSkillSlugs: ['machine-learning'],
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'deep-learning',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 60,
    prerequisiteSkillSlugs: ['machine-learning', 'python'],
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'regression',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 20,
    prerequisiteSkillSlugs: ['statistics'],
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'classification',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 20,
    prerequisiteSkillSlugs: ['statistics', 'machine-learning'],
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'hypothesis-testing',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 15,
    prerequisiteSkillSlugs: ['statistics'],
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'sql',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'data-visualization',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'data-cleaning',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'research-design',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'data-scientist',
    skillSlug: 'communication',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 10,
  },

  // ─── ML Engineer ───────────────────────────────────────────────────────
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'python',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 50,
  },
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'machine-learning',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 60,
    prerequisiteSkillSlugs: ['python'],
  },
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'docker',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'etl',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 30,
  },
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'rest-api',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'ci-cd',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'aws',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 40,
  },
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'model-evaluation',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 20,
    prerequisiteSkillSlugs: ['machine-learning'],
  },
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'linux',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'data-cleaning',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'testing',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'kubernetes',
    requiredLevel: 2,
    importance: 'low',
    estimatedEffortHours: 40,
  },
  {
    careerSlug: 'machine-learning-engineer',
    skillSlug: 'problem-solving',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 10,
  },

  // ─── Software Engineer ─────────────────────────────────────────────────
  {
    careerSlug: 'software-engineer',
    skillSlug: 'javascript',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 50,
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'git',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 10,
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'rest-api',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'testing',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'data-modeling',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'nodejs',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 30,
    prerequisiteSkillSlugs: ['javascript'],
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'express',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 15,
    prerequisiteSkillSlugs: ['nodejs'],
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'mongodb',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 20,
    prerequisiteSkillSlugs: ['data-modeling'],
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'postgresql',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 20,
    prerequisiteSkillSlugs: ['sql', 'data-modeling'],
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'sql',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'docker',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'ci-cd',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 25,
    prerequisiteSkillSlugs: ['git', 'testing'],
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'linux',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'problem-solving',
    requiredLevel: 4,
    importance: 'high',
    estimatedEffortHours: 10,
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'web-security',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'attention-to-detail',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 8,
  },
  {
    careerSlug: 'software-engineer',
    skillSlug: 'teamwork',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 8,
  },

  // ─── Web Developer ─────────────────────────────────────────────────────
  {
    careerSlug: 'web-developer',
    skillSlug: 'html',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'css',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 35,
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'javascript',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 50,
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'react',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 50,
    prerequisiteSkillSlugs: ['javascript'],
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'responsive-design',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'accessibility',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'rest-api',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 20,
    prerequisiteSkillSlugs: ['javascript'],
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'git',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 10,
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'typescript',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 20,
    prerequisiteSkillSlugs: ['javascript'],
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'web-security',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'web-performance',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'nodejs',
    requiredLevel: 2,
    importance: 'low',
    estimatedEffortHours: 25,
    prerequisiteSkillSlugs: ['javascript'],
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'time-management',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 8,
  },
  {
    careerSlug: 'web-developer',
    skillSlug: 'teamwork',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 8,
  },

  // ─── Cybersecurity Analyst ─────────────────────────────────────────────
  {
    careerSlug: 'cybersecurity-analyst',
    skillSlug: 'networking',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 45,
  },
  {
    careerSlug: 'cybersecurity-analyst',
    skillSlug: 'linux',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 30,
  },
  {
    careerSlug: 'cybersecurity-analyst',
    skillSlug: 'threat-detection',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 40,
    prerequisiteSkillSlugs: ['networking', 'linux'],
  },
  {
    careerSlug: 'cybersecurity-analyst',
    skillSlug: 'web-security',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 30,
  },
  {
    careerSlug: 'cybersecurity-analyst',
    skillSlug: 'python',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 30,
  },
  {
    careerSlug: 'cybersecurity-analyst',
    skillSlug: 'sql',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'cybersecurity-analyst',
    skillSlug: 'docker',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'cybersecurity-analyst',
    skillSlug: 'data-analysis',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'cybersecurity-analyst',
    skillSlug: 'technical-writing',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 12,
  },
  {
    careerSlug: 'cybersecurity-analyst',
    skillSlug: 'critical-thinking',
    requiredLevel: 4,
    importance: 'high',
    estimatedEffortHours: 10,
  },
  {
    careerSlug: 'cybersecurity-analyst',
    skillSlug: 'attention-to-detail',
    requiredLevel: 4,
    importance: 'high',
    estimatedEffortHours: 8,
  },

  // ─── UI/UX Designer ────────────────────────────────────────────────────
  {
    careerSlug: 'ui-ux-designer',
    skillSlug: 'figma',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 40,
  },
  {
    careerSlug: 'ui-ux-designer',
    skillSlug: 'ui-design',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 50,
  },
  {
    careerSlug: 'ui-ux-designer',
    skillSlug: 'ux-design',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 50,
  },
  {
    careerSlug: 'ui-ux-designer',
    skillSlug: 'prototyping',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'ui-ux-designer',
    skillSlug: 'accessibility',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'ui-ux-designer',
    skillSlug: 'html',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'ui-ux-designer',
    skillSlug: 'css',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'ui-ux-designer',
    skillSlug: 'communication',
    requiredLevel: 4,
    importance: 'high',
    estimatedEffortHours: 12,
  },
  {
    careerSlug: 'ui-ux-designer',
    skillSlug: 'presentation',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 10,
  },
  {
    careerSlug: 'ui-ux-designer',
    skillSlug: 'research-design',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'ui-ux-designer',
    skillSlug: 'teamwork',
    requiredLevel: 4,
    importance: 'high',
    estimatedEffortHours: 10,
  },
  {
    careerSlug: 'ui-ux-designer',
    skillSlug: 'critical-thinking',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 10,
  },

  // ─── Cloud Engineer ────────────────────────────────────────────────────
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'aws',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 60,
  },
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'linux',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 30,
  },
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'docker',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'networking',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 30,
  },
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'kubernetes',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 45,
    prerequisiteSkillSlugs: ['docker'],
  },
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'ci-cd',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 25,
    prerequisiteSkillSlugs: ['linux'],
  },
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'terraform',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 30,
  },
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'web-security',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'python',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'shell',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'problem-solving',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 10,
  },
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'monitoring',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'cloud-engineer',
    skillSlug: 'technical-writing',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 10,
  },

  // ─── Digital Marketing Specialist ──────────────────────────────────────
  {
    careerSlug: 'digital-marketing-specialist',
    skillSlug: 'seo',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 40,
  },
  {
    careerSlug: 'digital-marketing-specialist',
    skillSlug: 'content-strategy',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 30,
  },
  {
    careerSlug: 'digital-marketing-specialist',
    skillSlug: 'social-media',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'digital-marketing-specialist',
    skillSlug: 'paid-advertising',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 35,
  },
  {
    careerSlug: 'digital-marketing-specialist',
    skillSlug: 'google-analytics',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'digital-marketing-specialist',
    skillSlug: 'data-analysis',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'digital-marketing-specialist',
    skillSlug: 'copywriting',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'digital-marketing-specialist',
    skillSlug: 'ab-testing',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 15,
    prerequisiteSkillSlugs: ['data-analysis'],
  },
  {
    careerSlug: 'digital-marketing-specialist',
    skillSlug: 'communication',
    requiredLevel: 4,
    importance: 'high',
    estimatedEffortHours: 10,
  },
  {
    careerSlug: 'digital-marketing-specialist',
    skillSlug: 'project-management',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 12,
  },
  {
    careerSlug: 'digital-marketing-specialist',
    skillSlug: 'presentation',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 10,
  },

  // ─── Business Analyst ──────────────────────────────────────────────────
  {
    careerSlug: 'business-analyst',
    skillSlug: 'requirements-gathering',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 30,
  },
  {
    careerSlug: 'business-analyst',
    skillSlug: 'data-analysis',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'business-analyst',
    skillSlug: 'excel',
    requiredLevel: 3,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'business-analyst',
    skillSlug: 'sql',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'business-analyst',
    skillSlug: 'stakeholder-management',
    requiredLevel: 4,
    importance: 'high',
    isCore: true,
    estimatedEffortHours: 20,
  },
  {
    careerSlug: 'business-analyst',
    skillSlug: 'business-analysis',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 25,
  },
  {
    careerSlug: 'business-analyst',
    skillSlug: 'process-mapping',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 18,
  },
  {
    careerSlug: 'business-analyst',
    skillSlug: 'data-visualization',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 18,
  },
  {
    careerSlug: 'business-analyst',
    skillSlug: 'power-bi',
    requiredLevel: 2,
    importance: 'medium',
    estimatedEffortHours: 20,
    prerequisiteSkillSlugs: ['excel'],
  },
  {
    careerSlug: 'business-analyst',
    skillSlug: 'project-management',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 15,
  },
  {
    careerSlug: 'business-analyst',
    skillSlug: 'communication',
    requiredLevel: 4,
    importance: 'high',
    estimatedEffortHours: 10,
  },
  {
    careerSlug: 'business-analyst',
    skillSlug: 'presentation',
    requiredLevel: 3,
    importance: 'medium',
    estimatedEffortHours: 12,
  },
  {
    careerSlug: 'business-analyst',
    skillSlug: 'critical-thinking',
    requiredLevel: 3,
    importance: 'high',
    estimatedEffortHours: 10,
  },
];
